apiVersion: v1
kind: pod
spec:
containers:
- name: gradle
  image: gradle:6.3-jdk14
  command:
  - sleep
  args:
  - 99d
  volumeMounts:
  - name: jenkins-home
    mountPath: /mnt
- name: kaniko
  image: gcr.io/kaniko-project/executor:debug
  command:
  - sleep
  args:
  - 9999999
  volumeMounts:
  - name: jenkins-home
    mountPath: /mnt
  - name: kaniko-secret
    mountPath: /kaniko/.docker
restartPolicy: Never
volumes:
- name: jenkins-home
  persistentVolumeClaim:
    claimName: jenkins-pv-claim
- name: kaniko-secret
  secret:
      secretName: dockercred
      items:
      - key: .dockerconfigjson
        path: config.json
