apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-persistent-volume
  labels:
    type: local
spec:
  storageClassName: hostpath
  claimRef:
    name: jenkins-pv-claim
    namespace: devops-tools
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp
  persistentVolumeReclaimPolicy: Retain



